// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysvbwnjaimwmzojkykki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdmJ3bmphaW13bXpvamt5a2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTU5ODMsImV4cCI6MjA2MTA5MTk4M30.c_cNodMXdqlr4-AbZ3Y5FjLF0ZXAguv6uakpGUFyyCk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);